### ISSUE TITLE
What prediction mask suze

### ISSUE THREAD

**Issue by RespectKnowledge** [KiPA2022/kipa22#4]
Thank you for your great efforts to launch this challenge and providing good code. I have basic question. You used cropped 128 shape during training. How the prediction function produce the  size of mask as input image size because test or validation volume has different sizes? Thank you very much in advance.

**Comment by KiPA2022** [comment]
Dear participant,
Thank you for asking such a valuable question, but it is a technical question. However, we will not provide any suggestions on it, Because it would be against the fairness of the challenge. The open reference code we provided uses the unfixed image size to test directly, but this does not mean that it is the best method. We encourage participants to try better methods to obtain the final test results.
KiPA2022
________________________________
发件人: Abdul Qayyum ***@***.***>
发送时间: 2022年6月26日 9:47
收件人: KiPA2022/kipa22 ***@***.***>
抄送: Subscribed ***@***.***>
主题: [KiPA2022/kipa22] What prediction mask suze (Issue #4)


Thank you for your great efforts to launch this challenge and providing good code. I have basic question. You used cropped 128 shape during training. How the prediction function produce the size of mask as input image size because test or validation volume has different sizes? Thank you very much in advance.

―
